### ISSUE TITLE
Employees cannot be updated properly to a service

### ISSUE THREAD

**Issue by AymenMetallaoui** [kevinlizh1992/rtterror#13]
Updating employee information to a service does not remove old information present in the database.

**Comment by AymenMetallaoui** [comment]
This issue is closed after the backend refactoring to TypeScript : pull request #25

**Comment by AymenMetallaoui** [comment]
**### Bug Report**

**1.Bug URL:**

commit be157e8 in services.services-employees.js

However, the defective code has not been committed.

**2.Date Created:**

Nov 7, 2021

**3.Defect Description:**

The addition of the employee CRUD on the service side with a database related to the specific module was linked to the frontend part. The Frontend could not update properly the specific employee related to a certain service. 

For example, some employees informations would not make sense with the new employee as the old information would still be part of the service. 

**4.Resolution:**

Changing the structure of the code to the TypeScript method helped clear out the issue as the data is properly structured and transmitted from backend to frontend.

**5.Resolution Date:**

Jan 25, 2022

**6.Screenshot Bug:**

X

**Comment by successsb89** [comment]
After changing the structure of the code, this bug resolved. Therefore, we close this bug issue.
