### ISSUE TITLE
Creating a new service works but does not show in front end UI

### ISSUE THREAD

**Issue by AymenMetallaoui** [kevinlizh1992/rtterror#14]
Clicking on create a new service affects the backend properly but does not load a new front end page .

**Comment by AymenMetallaoui** [comment]
### Bug Report

**1.Bug URL:**

commit b6569bc from feature/merge-frontend branch

**2.Date Created:**

Nov 7, 2021

**3.Defect Description:**

Adding a new service in the frontend updates the backend and database properly but it would not show any difference in the frontend. The new service options and data would not be shown as visual when doing this maneuver .

**4.Resolution:**

Updating the state of the page after a change in the backend data of the service so it gives the proper options and displays  a new view. 

**5.Resolution Date:**

Jan 25, 2022

**6.Screenshot Bug:**

X

**Comment by successsb89** [comment]
bug was resolved from the previous sprint. Therefore, we close this bug issue.
