### ISSUE TITLE
Need to refactor Services

### ISSUE THREAD

**Issue by yuxiang-zhang** [kevinlizh1992/rtterror#23]
In #22, I also started to add tests for Service module services, but I found that feature code in the module need to be refactored before moving on. As it currently is, the test code is unable to test functions separately. Specifically, `sequelize` poses most of the problem: `sequelize` authentication fails when invoked in test files; the models are not being created in `sequelize`. Additionally, `sequelize` seems to be coupled with `server.ts`. `server.ts` should be in fact `app.ts`, as an Express app, not a server, is returned. According to [this article](https://www.albertgao.xyz/2017/05/24/how-to-test-expressjs-with-jest-and-supertest#2-Separate-your-app-and-server), it is best to separate `app` and `server`.

**Comment by successsb89** [comment]
If this is the issue and we need to refactor Services, @Alex-DSJ , can you take a look and give us your thought?
