### ISSUE TITLE
Unable Update Employee is not working

### ISSUE THREAD

**Issue by kimchhengheng** [kevinlizh1992/rtterror#33]
When updating the existing employee, the error occurs. 
PUT :  http://localhost:5000/api/v1/employees/
{
        "id": "9f2e2955-b615-42e9-98be-5bded5b663e3",
        "first_name": "kimmmmm",
        "last_name": "chheng ",
        "gender": null,
        "dob": "emp",
        "sin": "emp",
        "address": "emp",
        "postal_code": "emp",
        "phone": "emp",
        "email": "emp",
        "title": "emp",
        "start_date": "2022-01-27T02:41:01.000Z",
        "end_date": null,
        "hidden": false, 
        "services": []
   }
   response: 
{
    "generatedMessage": false,
    "code": "ERR_ASSERTION",
    "expected": true,
    "operator": "=="
}

**Comment by taufiqueahmed** [comment]
# Bug Report Format

---
## 1.Bug URL:

_https://github.com/kevinlizh1992/rtterror/issues/33#issue-1115724066_

## 2.Date Created: 

_Jan,26,2022_

## 3.Defect Description:
 
_When updating the existing employee an error occurs.._

## 4.Resolution: 
_Yet to be resolved_

## 5.Resolution Date:
_Not yet solved_

## 6.Screenshot Bug: 
_PUT : http://localhost:5000/api/v1/employees/
{
"id": "9f2e2955-b615-42e9-98be-5bded5b663e3",
"first_name": "kimmmmm",
"last_name": "chheng ",
"gender": null,
"dob": "emp",
"sin": "emp",
"address": "emp",
"postal_code": "emp",
"phone": "emp",
"email": "emp",
"title": "emp",
"start_date": "2022-01-27T02:41:01.000Z",
"end_date": null,
"hidden": false,
"services": []
}
response:
{
"generatedMessage": false,
"code": "ERR_ASSERTION",
"expected": true,
"operator": "=="
}._

---

**Comment by Alex-DSJ** [comment]
the error comes from a misuse of a built-in sequelize method [update()](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-update). this method will return the number of affected rows instead of updated information. So we need to use [upsert()](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-upsert) method to get the updated employee Model for add services later in the method.

**Comment by successsb89** [comment]
This bug resolved from the PR #24 . We close this bug issue.
