### ISSUE TITLE
block/unblock multiple services with the same servide_code

### ISSUE THREAD

**Issue by Alex-DSJ** [kevinlizh1992/rtterror#35]
# Bug Report

---
## 1.Bug URL:

[commit#79dcd61a52a3cb067fbff310aabf4ca332411bfc](https://github.com/kevinlizh1992/rtterror/commit/79dcd61a52a3cb067fbff310aabf4ca332411bfc)

## 2.Date Created: 

Jan 27, 2022

## 3.Defect Description:

instead of block/unblock a single service, we now have the UI that allows the user to create multiple services which share the same information except for durations and prices, thus, we what to 

## 4.Resolution: 

modify the backend
1. change the route from accepting service id to `service_code`
2. create method `blockUnblockServices` to block or unblock the services of given `service_code`

## 5.Resolution Date:

Jan 28, 2022

## 6.Screenshot Bug: 

NA

---

**Comment by successsb89** [comment]
This bug is resolved. We close this bug issue.
