### ISSUE TITLE
The Service module's functionalities don't response from Front End side.

### ISSUE THREAD

**Issue by successsb89** [kevinlizh1992/rtterror#36]
# Bug Report Format

---
## 1.Bug URL:

#12 

## 2.Date Created: 

Jan.28 2022

## 3.Defect Description:

 Tested the functionalities of the Server module.
- [x] It doesn't response to create "New service", following this issue cannot verify further detailed functionalities as well. 
- [x] "Create combo" button doesn't active.

## 4.Resolution: 

It comes from the routing problem. 

## 5.Resolution Date:

Not Yet Resolved.

## 6.Screenshot Bug: 
![image](https://user-images.githubusercontent.com/46511438/151619527-ef518bf1-e7bd-4992-8c5b-eba0f1bffe48.png)

---

**Comment by kimchhengheng** [comment]
The create Combo only enables to click when there is at least one service check.

**Comment by successsb89** [comment]
The bugs resolved. We can now see all functionalities work properly on the service module. We close this bug issue.
