### ISSUE TITLE
Tests need to be changed to adapte backend modifications

### ISSUE THREAD

**Issue by Alex-DSJ** [kevinlizh1992/rtterror#39]
# Bug Report Format

---
## 1.Bug URL:

[Build server application error](https://github.com/kevinlizh1992/rtterror/runs/4994982851?check_suite_focus=true)

## 2.Date Created: 

Jan 30, 2022 with the PR #25 

## 3.Defect Description:

The basis of service CRUD operations is changed to be service_code because the services with the same basic info can have different durations and prices, for example, when the user create a service, it can enter multiple durations and prices combinations and the backend should create different services based on these durations and prices with the same values for all other attributes, the same condition applies to UPDATE and DELETE operation. the backend has been modified, but the JEST test should also be modified to adapte these changes

## 4.Resolution: 
_Description of the defect’s resolution._

## 5.Resolution Date:
_Date on which the defect is to be resolved (or is resolved depending upon its status)._

## 6.Screenshot Bug: 

![image](https://user-images.githubusercontent.com/55929166/151714279-2d7802fd-e65e-423e-875c-d3399c8ea82b.png)

---

**Comment by yuxiang-zhang** [comment]
Can we justify the removal of finding items by id? I understand that service codes can be used to retrieve services, but do we just not allow retrieving services by id? Maybe we could use `service/code/<service code>/` for that

**Comment by Alex-DSJ** [comment]
> Can we justify the removal of finding items by id? I understand that service codes can be used to retrieve services, but do we just not allow retrieving services by id? Maybe we could use `service/code/<service code>/` for that

yes, based on the mockup design, when creating services, we will create a group of services with the samebasic info such as service_code, name, etc., but different durations with corresponding prices, this condition also applies to other CRUD operations such as update, and deletion.
