### ISSUE TITLE
Search Employee does not work 

### ISSUE THREAD

**Issue by kimchhengheng** [kevinlizh1992/rtterror#40]
# Bug Report Format

---
## 1.Bug URL:

_Include the github bug url._

## 2.Date Created: 

The bug was found on 20222 / 01 /31.

## 3.Defect Description:

In the employee subtab, the search does not show the employee that matches the search input value.

## 4.Resolution: 
_Description of the defect’s resolution._

## 5.Resolution Date:
_Date on which the defect is to be resolved (or is resolved depending upon its status)._

## 6.Screenshot Bug: 
_An image of the bug for better understanding._

---
![searchdoesnotwork](https://user-images.githubusercontent.com/43865591/151910992-c129fb0c-8201-4f59-b9ec-465c6a9286c5.png)

**Comment by Alex-DSJ** [comment]
The backend did not implement such functionality and think this functionality can be implemented in the frontend, and the consideration is:

1. The state will be changed each time the search string changes, if we send a request each time the search string changes, it will emit a lot of HTTP requests which is not neccessary
2. The clinic is not a large company, the number of employees will be small, so we can filter the employee list on the flight in the frontend, the response will be much more quick than using a backend API

anyway, the implementation for such a functionality is not difficult, and if you do think that it is better to implement in the backend, please let me know.
