### ISSUE TITLE
Employee page is not displaying the required fields

### ISSUE THREAD

**Issue by yuxiang-zhang** [kevinlizh1992/rtterror#45]
# Bug Report Format

---
## 1.Bug URL:

`/employee`

## 2.Date ~Created~ Discovered: 

2022.1.21

## 3.Defect Description:

The following fields/columns must appear on the Employee list/table: 
- id (numeric)
- start/hire date
- phone number (instead of email). 

## 4.Resolution: 

Add the above fields. 

## 5.Resolution Date:

Not yet resolved. 

## 6.Screenshot Bug: 

![image](https://user-images.githubusercontent.com/23327251/153994784-e19026fb-c6fd-4cb3-b3b0-69479daf5e70.png)

---

**Comment by kimchhengheng** [comment]
Replace column
![image](https://user-images.githubusercontent.com/43865591/155267793-2ec619d7-d64b-4346-8359-6ff6f19f886b.png)

**Comment by kimchhengheng** [comment]
@Alex-DSJ  please change the Id to number instead of UUID?
