### ISSUE TITLE
Service Combo deletion should not cascade

### ISSUE THREAD

**Issue by yuxiang-zhang** [kevinlizh1992/rtterror#46]
# Bug Report Format

## 1.Bug URL:

`/service`

## 2.Date Created: 

2022.1.21

## 3.Defect Description:

The services and combos should be deleted independently, i.e. deleting one should not affect the other. 

## 4.Resolution: 
.

## 5.Resolution Date:
Not yet resolved

## 6.Screenshot Bug: 
![image](https://user-images.githubusercontent.com/23327251/153995558-12d72575-6253-40d4-bf5b-393f8f0f8a5e.png)

---

**Comment by kimchhengheng** [comment]
Remove the confirmation to delete from combo when delete service 
![image](https://user-images.githubusercontent.com/43865591/155266371-4648a6e6-a7a8-451c-afd0-c5d77f9ed3e3.png)

**Comment by kimchhengheng** [comment]
@Alex-DSJ : please review the Backend part for this ?

**Comment by Alex-DSJ** [comment]
@yuxiang-zhang the problem is our combo is made up of base services, if we delete one base service, what should we do to the associated combo? simply delete that base service from the combos and keep others the same?

**Comment by yuxiang-zhang** [comment]
> @yuxiang-zhang the problem is our combo is made up of base services, if we delete one base service, what should we do to the associated combo? simply delete that base service from the combos and keep others the same?

The service will not be deleted but simply hidden from view. The combo will thus not be affected by the delete; the corresponding service in the combo will continue to exist and be used as before. Deleted/hidden services will not be used in future appointments and cannot be part of any *new* combos.

**Comment by Alex-DSJ** [comment]
> 

ok
