### ISSUE TITLE
Service display issues

### ISSUE THREAD

**Issue by yuxiang-zhang** [kevinlizh1992/rtterror#47]
# Bug Report Format

## 1.Bug URL:

`/service`

## 2.Date Created: 

2022.1.21

## 3.Defect Description:

Several small issues related to the display of services in Service module: 

- [x] display duration of service in *minutes* instead of *hours*
- [x] blocked services should appear at the bottom or be hidden from view (togglable)
- [x] services and combos should be displayed in two panels side by side

## 4.Resolution: 
See above checklist: commit hash should be appended to the list item.

## 5.Resolution Date:
Not yet resolved

## 6.Screenshot Bug: 
![image](https://user-images.githubusercontent.com/23327251/153996058-07634e01-42b5-4dea-848a-a5050ea90a0e.png)

![image](https://user-images.githubusercontent.com/23327251/153996126-fb0e0b63-af53-4b9e-8e62-e676cf2bb649.png)

![image](https://user-images.githubusercontent.com/23327251/153996163-b492688f-9300-48de-b38c-41f58dc89464.png)

---

**Comment by kimchhengheng** [comment]
After fix: 
![image](https://user-images.githubusercontent.com/43865591/155261476-2a1afa3c-c84f-4a81-be59-410107caa08e.png)
![image](https://user-images.githubusercontent.com/43865591/155263070-149ddeda-7188-4736-98d7-1ea736e22ffc.png)
![image](https://user-images.githubusercontent.com/43865591/155263584-3838edb7-7954-4687-9b54-752cc2773fe1.png)
