### ISSUE TITLE
Appointment does not store duration as an attribute

### ISSUE THREAD

**Issue by yuxiang-zhang** [kevinlizh1992/rtterror#57]
# Bug Report

---
## 1.Bug URL:

Request GET `/api/v1/appointments`

## 2.Date Created: 

#55 

## 3.Defect Description:

The response returns a start `datetime` for appointments but does not specify the duration of the appointments. The duration may be calculated from the sum of all services associated with the appointment but should also allow client to input an arbitrary value. 

## 4.Resolution: 

I propose to add a duration attribute and put a default value. 

## 5.Resolution Date:

TBD. 

## 6.Screenshot Bug: 

N/A

**Comment by Alex-DSJ** [comment]
the appointment duraion can be determined by adding up all service durations, but it is reasonable to allow the user the define one, I will fix it by changing the appointment schema
